include_guard(DIRECTORY)
include("${CMAKE_CURRENT_LIST_DIR}/init/options.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/init/modules.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/init/dependencies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/init/languages.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/init/generate.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/init/build.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/init/tools.cmake")
