# generation
include(GenerateExportHeader)

function(generate_preset_export_header LIBRARY_TARGET)
	string(REPLACE "-" "_" LIBRARY_TARGET_CODE "${LIBRARY_TARGET}")
	string(TOUPPER "${LIBRARY_TARGET_CODE}" LIBRARY_TARGET_CODE_UPPER)
	set(CUSTOM_EXPORT_HEADER "
#ifdef ${LIBRARY_TARGET_CODE_UPPER}_STATIC_DEFINE
#	define ${LIBRARY_TARGET_CODE_UPPER}_EXPORT_DECLARATION
#	define ${LIBRARY_TARGET_CODE_UPPER}_EXPORT_DEFINITION
#else
#	ifndef ${LIBRARY_TARGET_CODE_UPPER}_EXPORT_DECLARATION
#		ifdef ${LIBRARY_TARGET_CODE}_EXPORTS
#			ifdef _MSC_VER
#				define ${LIBRARY_TARGET_CODE_UPPER}_EXPORT_DECLARATION
#			else
#				define ${LIBRARY_TARGET_CODE_UPPER}_EXPORT_DECLARATION ${LIBRARY_TARGET_CODE_UPPER}_EXPORT
#			endif
#		else
#			define ${LIBRARY_TARGET_CODE_UPPER}_EXPORT_DECLARATION ${LIBRARY_TARGET_CODE_UPPER}_EXPORT
#		endif
#	endif
#	ifndef ${LIBRARY_TARGET_CODE_UPPER}_EXPORT_DEFINITION
#		ifdef ${LIBRARY_TARGET_CODE}_EXPORTS
#			ifdef _MSC_VER
#				define ${LIBRARY_TARGET_CODE_UPPER}_EXPORT_DEFINITION ${LIBRARY_TARGET_CODE_UPPER}_EXPORT
#			else
#				define ${LIBRARY_TARGET_CODE_UPPER}_EXPORT_DEFINITION
#			endif
#		else
#			define ${LIBRARY_TARGET_CODE_UPPER}_EXPORT_DEFINITION
#		endif
#	endif
#endif
")
	generate_export_header("${LIBRARY_TARGET}"
		EXPORT_FILE_NAME "include/${LIBRARY_TARGET}/export.h"
		CUSTOM_CONTENT_FROM_VARIABLE CUSTOM_EXPORT_HEADER)
endfunction()
